name: Publish PHAR

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: tag
        run: echo "tag=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL, phar.readonly=Off
          tools: composer:v2
          coverage: none

      - run: composer install --prefer-dist --optimize-autoloader --no-interaction --no-progress --no-scripts --ansi -v --ignore-platform-req=ext-pcntl --ignore-platform-req=ext-posix --ignore-platform-req=ext-sockets

      - run: php screentest app:build screentest.phar --build-version=${{ steps.tag.outputs.tag }} -v

      - uses: actions/upload-artifact@v4
        with:
          name: screentest.phar
          path: builds/screentest.phar

      - run: gh release upload ${{ github.event.release.tag_name }} builds/screentest.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: cp builds/screentest.phar builds/screentest
